### ISSUE TITLE
[Request] - Mod Continuation.

### ISSUE THREAD

**Issue by XvBUSHvX** [LothrazarMinecraftMods/InventoryCrafting#2]
I have been looking for a mod that implements the 3x3 crafting matrix into the inventory, much like this mod does, but for 1.12.2. There are a few other mods that provide this functionality but generally include many features outside the concept of the pack I'm designing. I had initiated contact with the developer of CraftingTweaks and CraftingCraft to see if this was something they were interested in doing. The response highlighted a few issues I hadn't considered, and conveyed that such project wasn't within the scope of the CraftingCraft project and would be an independent mod if they were to work on it at some point. As well as directing me to this project, which I hope that interest in this mod may sway you to continue on with it. 

Possible considerations if you do feel up to updating;

Outside of the Vanilla Recipe Book there are other mods which adds a button of their own in the gui space around the 2x2 matrix. 

There is also the addition of the shield slot limiting the available space. 

A separate gui within the inventory is possible solution to the space issues and to reduce potential conflicts with other mods. A discrete, relocatable, button near the player model that opens to a different gui, similar to baubles interface, could be functional and stylish solution. 

I thank you for your time and consideration, keep up the great work.

**Comment by Lothrazar** [comment]
It is now out for modern versions, including 1.15.2  

Currently it is not a seperate GUI, right now it replaces the existing inventory, and is compatible with Curios and JEI
