### ISSUE TITLE
[Enhancement] Use inventory slots as crafting grid

### ISSUE THREAD

**Issue by supersaiyansubtlety** [LothrazarMinecraftMods/InventoryCrafting#5]
Just as a suggestion: you may be able to improve compatibility and simplify implementation if you use the player's existing inventory slots as your crafting grid, much like [CraftingCraft](https://www.curseforge.com/minecraft/mc-mods/craftingcraft)'s inventory crafting pad. If you don't want to replace the existing implementation (which is admittedly more intuitive), it would also be useful as an additional compatibility configuration.

**Comment by Lothrazar** [comment]
That would be a really cool feature, but im in no rush to go that direction.
Thats a good idea for a different standalone mod though :)

**Comment by supersaiyansubtlety** [comment]
Sounds good, and also thanks for the mod!
